app/Http/routes.php
<?php

# ------------------ Page Route ------------------------
Route::get('/', 'PagesController@home')->name('home');
Route::get('/feed', 'PagesController@feed')->name('feed');
Route::get('/sitemap', 'PagesController@sitemap');
Route::get('/sitemap.xml', 'PagesController@sitemap');
Route::get('/search', 'PagesController@search')->name('search');

Route::group(['middleware' => ['auth', 'admin_auth']], function () {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

// Registration Routes... 请自行开启注册功能
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...  请自行开启注册功能
// Route::get('password/reset', 'Auth\PasswordController@getEmail');
// Route::post('password/email', 'Auth\PasswordController@postEmail');
// Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
// Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::resource('users', 'UsersController', ['only' => ['show']]);
Route::resource('posts', 'PostController', ['only' => ['show', 'create', 'store', 'update', 'edit']]);
Route::resource('categories', 'CategoryController', ['only' => ['show']]);

Route::resource("issues","IssueController", ['only' => ['show', 'index']]);

app/Models/Post.php
<?php

namespace App\Models;

class Post extends BaseModel
{
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function issue()
    {
        return $this->belongsTo(Issue::class);
    }

    public function Category()
    {
        return $this->belongsTo(Category::class);
    }

    public function setBodyOriginalAttribute($value)
    {
        $this->attributes['body'] = markdown($value);
        $this->attributes['body_original'] = $value;
    }

    public function setCoverAttribute($file_name)
    {
        if (strpos($file_name, 'http') !== false) {
            $this->attributes['cover'] = $file_name;
        } else {
            $this->attributes['cover'] = 'uploads/covers/'.$file_name;
        }
    }

    public function getCoverAttribute($file_name)
    {
        if (starts_with($file_name, 'http')) {
            return $file_name;
        }

        return cdn($file_name);
    }

    public function scopeUnissued($query)
    {
        return $query->where('issue_id', '0');
    }

    public static function issuePostsByCid($cid, $issue_id = 0)
    {
        if ($issue_id == 0)  {
            return static::where('category_id', $cid)
                            ->unissued()
                            ->ordered()
                            ->recent()
                            ->get();
        } else {
            return static::where('category_id', $cid)
                            ->where('issue_id', $issue_id)
                            ->ordered()
                            ->recent()
                            ->get();
        }

    }

}

app/Http/Controllers/PostController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Post;
use App\Models\Category;
use Illuminate\Http\Request;
use Auth;

use App\Http\Requests\StorePostRequest;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    public function create(Request $request)
    {
        $category = Category::find($request->input('category_id'));
        $categories = Category::all();
        return view('posts.create_edit', compact('categories', 'category'));
    }

    public function store(StorePostRequest $request)
    {
        $data = $request->only('title','body_original','category_id','cover', 'excerpt');
        $data['user_id'] = Auth::id();
        $post = Post::create($data);

        return redirect(route('posts.show', $post->id));
    }

    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $categories = Category::all();
        $category = $post->category;

        return view('posts.create_edit', compact('post', 'categories', 'category'));
    }

    public function update($id, StorePostRequest $request)
    {
        $post = Post::findOrFail($id);
        $post->update($request->only('title','body_original','category_id','cover', 'excerpt'));

        return redirect(route('posts.show', $post->id));
    }

	public function index()
	{
		$posts = Post::recent()->paginate(10);

		return view('posts.index', compact('posts'));
	}

	public function show($id)
	{
		$post = Post::where('id', $id)->with('user', 'category')->first();
        $posts = Post::recent()->paginate(3);

		return view('posts.show', compact('post', 'posts'));
	}
}

resources/views/posts/create_edit.blade.php
@extends('layouts.default')

@section('title')
{{ isset($post) ? '编辑文章' : '新建文章' }}_@parent
@stop

@section('content')

<div class="post-composing-box">
        <div class="text-center header">
            <h1>创作文章</h1>
        </div>
      @if (isset($post))
        <form method="POST" action="{{ route('posts.update', $post->id) }}" accept-charset="UTF-8" id="post-create-form">
        <input name="_method" type="hidden" value="PATCH">
      @else
          <form method="POST" action="{{ route('posts.store') }}" accept-charset="UTF-8" id="post-create-form">
      @endif

        @include('error')

        {!! csrf_field() !!}

        <div class="form-group">
            <select class="selectpicker form-control" name="category_id" id="category-select">

              <option value="" disabled {{ count($category) != 0 ?: 'selected' }}>请选择分类</option>
                  @foreach ($categories as $value)
                      <option value="{{ $value->id }}" {{ (count($category) != 0 && $value->id == $category->id) ? 'selected' : '' }} >{{ $value->name }}</option>
                  @endforeach
            </select>
        </div>

        <div class="form-group">
            <input class="form-control" placeholder="文章标题" name="title" type="text" value="{{ old('title') ?: (isset($post) ? $post->title : '') }}">
        </div>

        <div class="form-group">
            <input class="form-control" placeholder="文章封面，请到 laravel-china.org 上随便找个帖子评论框上传图片来获取 HTTPS 的 URL ！" name="cover" type="text" value="{{ old('cover') ?: (isset($post) ? $post->cover : '') }}">
        </div>

        <div class="form-group">
            <input class="form-control" placeholder="100 字概述，在列表页面和邮件中会用到，请认真填写。" name="excerpt" type="text" value="{{ old('excerpt') ?: (isset($post) ? $post->excerpt : '') }}" required="required">
        </div>

        <div class="form-group">
            <textarea class="form-control" placeholder="文章内容" name="body_original" cols="50">{{ old('body_original') ?: (!isset($post) ? '' : $post->body_original) }}</textarea>
        </div>

        <div class="form-group status-post-submit">
            <input class="btn btn-primary" id="post-create-submit" type="submit" value="发布">
        </div>
    </form>

</div>

@stop

@section('scripts')
<script type="text/javascript">
    $(document).ready(function()
    {
        var simplemde = new SimpleMDE({
            spellChecker: false,
            autosave: {
                enabled: true,
                delay: 1,
                unique_id: "topic_content{{ isset($post) ? $post->id : '' }}"
            },
            forceSync: true
        });
    });

</script>
@stop

resources/views/posts/show.blade.php
@extends('layouts.default')

@section('title', $post->title . ' | ')

@section('content')
<div class="row colom-container">

    <main class="col-md-9 main-content">

        <article id="70" class="post">

            <section class="featured-media">
                <img src="{{ img_crop($post->cover, 1024, 546) }}" alt="{{ $post->title }}">
            </section>

            <header class="post-head">
                <h1 class="post-title">{{ $post->title }}</h1>
                <section class="post-meta">
                    <time class="post-date" title="{{ $post->created_at }}"><i class="fa fa-clock-o" aria-hidden="true"></i> {{ $post->created_at }}</time>
                </section>
            </header>

            <section class="post-content">

{!! $post->body !!}

            </section>

            <footer class="post-footer clearfix">
                <div class="pull-left tag-list">
                    <a href="{{ route('categories.show', [$post->category->id]) }}"><i class="fa fa-folder-open-o"></i> {{ $post->category->name }}</a>

                    @if (Auth::check())
                        | <a href="{{ route('posts.edit', [$post->id]) }}"><i class="fa fa-edit"></i> 修改文章</a>
                        | <a href="/admin/posts/{{ $post->id }}" target="_blank"><i class="fa fa-eye"></i> 后台查看</a>
                    @endif

                </div>

                <div class="pull-right share">
                    <div class="social-share-cs "></div>
                </div>

            </footer>


        </article>

        <div class="about-author clearfix">
            <a href="{{ route('users.show', $post->user->id) }}"><img src="{{ $post->user->avatar }}" alt="{{ $post->user->name }}" class="avatar pull-left"></a>

            <div class="details">
                <div class="author">
                    作者 <a href="{{ route('users.show', $post->user->id) }}">{{ $post->user->name }}</a>
                </div>
                <div class="meta-info">
                    <div class="website"><i class="fa fa-globe"></i><a href="{{ $post->user->personal_website }}" targer="_blank"> 个人中心</a></div>
                    <div class="introduction"><i class="fa fa-paint-brush"></i>
                        {{ $post->user->introduction }}
                    </div>
                </div>
            </div>
        </div>

        <div class="bg-white recomanded-box">
            @include('_home_cell', ['section_title' => '推荐阅读', 'posts' => $posts])
        </div>


    </main>

    <aside class="col-md-3 sidebar">
        @include('layouts.partials.sidebar')
    </aside>




</div>

@endsection


@section('scripts')
<script type="text/javascript">

    $(document).ready(function()
    {
        var $config = {
            title               : '{{{ $post->title }}} from Laravel 资讯 #lara资讯',
            wechatQrcodeTitle   : "微信扫一扫：分享", // 微信二维码提示文字
            wechatQrcodeHelper  : '<p>微信里点“发现”，扫一下</p><p>二维码便可将本文分享至朋友圈。</p>',
            sites               : ['weibo','wechat',  'facebook', 'twitter', 'google','qzone', 'qq', 'douban'],
        };

        socialShare('.social-share-cs', $config);
    });

</script>
@stop