app/Http/routes.php
<?php

# ------------------ Page Route ------------------------
Route::get('/', 'PagesController@home')->name('home');
Route::get('/feed', 'PagesController@feed')->name('feed');
Route::get('/sitemap', 'PagesController@sitemap');
Route::get('/sitemap.xml', 'PagesController@sitemap');
Route::get('/search', 'PagesController@search')->name('search');

Route::group(['middleware' => ['auth', 'admin_auth']], function () {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

// Registration Routes... 请自行开启注册功能
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...  请自行开启注册功能
// Route::get('password/reset', 'Auth\PasswordController@getEmail');
// Route::post('password/email', 'Auth\PasswordController@postEmail');
// Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
// Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::resource('users', 'UsersController', ['only' => ['show']]);
Route::resource('posts', 'PostController', ['only' => ['show', 'create', 'store', 'update', 'edit']]);
Route::resource('categories', 'CategoryController', ['only' => ['show']]);

Route::resource("issues","IssueController", ['only' => ['show', 'index']]);

resources/views/layouts/partials/errors.blade.php
@if( $errors->any())
    <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/partials/footer.blade.php
<footer class="mastfoot offwhite-bg">
    <section class="inner-section social-wrap">
        <div class="container-fluid">
            <div class="row">
                <article class="col-md-6 col-md-offset-3 text-center foot-logo">

                    <p class="friend-links">
                        <a href="https://laravel-china.org/">LC 社区</a>
                        <a href="https://laravel-china.org/docs/home">中文文档</a>
                        <a href="https://cs.laravel-china.org/">速查表</a>
                        <a href="https://laravel-china.org/categories/1">Laravel 工作</a>
                        <a href="https://laravel-china.org/laravel-tutorial/5.1/about">入门教程</a>
                        <a href="{{ route('issues.index') }}">周刊存档</a>
                    </p>

                    <a href="index.html"><img alt="" title="" src="/assets/images/icon.png" /></a>

                    <p class="credits font2 dark add-top-quarter icons">
                        <a href="/assets/images/qrcode_new.png" class="icon-wechat">
                            <i class="fa fa-weixin" aria-hidden="true"></i>
                        </a>
                        <a href="http://weibo.com/laravelnews" class="icon-weibo">
                            <i class="fa fa-weibo" aria-hidden="true"></i>
                        </a>
                        <a href="https://github.com/summerblue/news.laravel-china.org" class="icon-github">
                            <i class="fa fa-github-alt" aria-hidden="true"></i>
                        </a>
                    </p>
                    <p class="credits font2  add-top-quarter">
                        由 <a href="https://github.com/summerblue" target="_blank">Summer</a> 设计与编码。
                        <hr style="border-top: 1px solid #4c4c4c;width: 320px;">
                        <a href="http://estgroupe.com/" style="color:#a5a5a5">
                            <img class="brand-icon" src="https://dn-phphub.qbox.me/uploads/images/201612/12/1/iq7WQc2iuW.png" ><span style="margin-top: 7px;display: inline-block;">
                                优帆远扬 | 创造不息，交付不止
                            </span>
                        </a>
                    </p>
                </article>
            </div>
        </div>
    </section>
</footer>

resources/views/layouts/partials/jobs_card.blade.php
<header class="card__header">
    <h2>Laravel 职位</h2>
    <img class="header__icon" src="/assets/images/min/icon-chair.png">
</header>
<div class="card__content">
    <p class="mb1">
        <a href="https://larajobs.com/job/594/intermediate-laravel-developer" class="link--white" rel="nofollow">
中高级 Laravel 工程师
</a>
    </p>
    <p class="mb1">
        <a href="https://larajobs.com/job/553/developer" class="link--white" rel="nofollow">
远程工作
</a>
    </p>
    <div class="m0">
        <a href="https://larajobs.com" class="link--teal">更多工作</a>
        <a href="https://larajobs.com" class="link--teal right">提交招聘</a>
    </div>
</div>

resources/views/layouts/partials/nav.blade.php
<div role="navigation" class="navbar navbar-default navbar-static-top topnav">
  <div class="container" style="margin-bottom:10px;">

      <div class="navbar-right">

        <ul class="nav navbar-nav github-login" style="margin-top:10px;">
          @if (Auth::check())
                @if (Auth::user()->can('visit_admin'))
                  <li>
                      <a href="/admin" class="text-md  ">
                          <i class="fa fa-tachometer"></i>
                      </a>
                  </li>
                @endif
              <li style="color:#e2e2e2">
                  <a href="{{route('users.show', $currentUser->id)}}">
                      <img class="avatar-topnav" alt="Summer" src="{{ $currentUser->present()->gravatar }}" style="width:25px;height:25px;margin-right:10px;"/>
                       {{{ $currentUser->name }}}
                  </a>
              </li>
              <li>
                  <a id="login-out" class="button" href="{{ URL::route('logout') }}" data-lang-loginout="你确定要退出吗">
                      <i class="fa fa-sign-out"></i> 退出
                  </a>
              </li>
          @else
              <a href="{{ URL::route('auth.oauth', ['driver' => 'wechat']) }}" class="btn btn-success login-btn weichat-login-btn">
                <i class="fa fa-weixin"></i>
                登录
              </a>

              <a href="{{ URL::route('auth.oauth', ['driver' => 'github']) }}" class="btn btn-info login-btn">
                <i class="fa fa-github-alt"></i>
                登录
              </a>
          @endif
        </ul>
      </div>
    </div>

  </div>
</div>

resources/views/layouts/partials/sidebar.blade.php
    <div class="widget rm-padding grid-item">
        <div class="grid-wrap subscribe-wrap">
            @include('layouts.partials.weekly_card', ['size' => 'small'])
        </div>
    </div>

    <div class="widget grid-item links">
        <div class="grid-wrap">
            <h4 class="title">推荐链接</h4>
            <a href="https://laravel-china.org/" class="btn btn-default btn-block" target="_blank">Laravel China 社区</a>
            <a href="https://laravel-china.org/docs/home" class="btn btn-default btn-block" target="_blank">Laravel 中文文档</a>
            <a href="https://cs.laravel-china.org/" class="btn btn-default btn-block" target="_blank">Laravel 速查表</a>
            <a href="https://easywechat.org/" class="btn btn-default btn-block" target="_blank"><i class="fa fa-wechat" aria-hidden="true"></i> Easy WeChat</a>
            <a href="https://lumen.laravel-china.org/" class="btn btn-default btn-block" target="_blank">Lumen 中文文档</a>
            <a href="https://laravel-china.org/laravel-tutorial/5.1/about" class="btn btn-default btn-block" target="_blank"><i class="fa fa-paper-plane" aria-hidden="true"></i> Laravel 入门教程</a>

            <a href="https://laravel-china.org/topics/3626" class="btn btn-default btn-block" target="_blank">Laravel 远程工作</a>
            <a href="https://yousails.com/" class="btn btn-default btn-block" target="_blank">技术服务 / 技术合作</a>
            <a href="https://yousails.com/waibao" class="btn btn-default btn-block" target="_blank">推荐外包，拿分成</a>
        </div>
    </div>


    <div class="widget grid-item">
        <div class="grid-wrap">
            <h4 class="title">关注订阅号</h4>
            <div class="content">
                <img src="/assets/images/qrcode_new.png" alt="" style="width:100%"/>
            </div>
        </div>
    </div>

resources/views/layouts/partials/topnav.blade.php
<div class="navbar navbar-default" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('home') }}">
                <span class="main-color text-bold">Laravel</span> 资讯</a>
          </div>

          <div class="navbar-collapse collapse">

            <!-- Left nav -->
            <ul class="nav navbar-nav" data-smartmenus-id="14739838239025269">
              <li><a href="{{ route('categories.show', [1]) }}">新闻</a></li>
              <li><a href="{{ route('categories.show', [2]) }}">教程</a></li>
              <li><a href="{{ route('categories.show', [4]) }}">资源</a></li>
              <li><a href="https://laravel-china.org/">论坛</a></li>
              <li><a href="https://doc.laravel-china.org/docs">文档</a></li>
              <li><a href="https://laravel-china.org/laravel-tutorial/5.1/about">Laravel 教程</a></li>
              <li><a href="{{ route('issues.index') }}">周刊</a></li>
              @if (Auth::check())
                <li><a href="{{ route('posts.create') }}"><i class="fa fa-plus"></i></a></li>
              @endif
            </ul>

            <!-- Right nav -->
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/assets/images/qrcode_new.png" class="icon-wechat">
                            <i class="fa fa-weixin" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li>
                        <a href="http://weibo.com/laravelnews" class="icon-weibo">
                            <i class="fa fa-weibo" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>

                <form method="GET" action="{{ route('search') }}" accept-charset="UTF-8" class="navbar-form navbar-left" target="_blank">
                    <div class="form-group">
                        <input class="form-control search-input mac-style" placeholder="搜索" name="q" type="text">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="search-btn">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </button>
                    </div>

                </form>
            </div>


          </div><!--/.nav-collapse -->


        </div><!--/.container -->
      </div>

resources/views/layouts/partials/weekly_card.blade.php
<div class="subscribe-box">
    <div class="subscribe-header">

        @if (isset($size) && $size == 'small')
            <h3>
                订阅周刊
                <i class="fa fa-envelope-o pull-right" aria-hidden="true"></i>
            </h3>
        @else
            <h2>
                订阅周刊
                <i class="fa fa-envelope-o pull-right" aria-hidden="true"></i>
            </h2>
        @endif
    </div>
    <div class="subscribe-content">

        @if (isset($size) && $size == 'small')
            <p>每周推送，让你不会错过任何关于 Laravel 的重要信息。</p>
        @else
            <p>每周推送 Laravel 最新资讯、精华文章、开发技巧、推荐扩展包、最新 Laravel 职位信息以及 「Laravel China 社区」上的精华讨论。</p>
        @endif
        <form action="https://laravelnews.createsend.com/t/d/s/owwr/" method="post" class="subscribe-form">

            @if (isset($size) && $size == 'small')
                <div class="input-group" style="width:100%">
                    <input class="form-control" placeholder="Email 地址" id="subscribe-input">
                    <span class="input-group-btn">
                        <button id="subscrib-btn" class="btn btn-danger btn-" type="button">订阅</button>
                    </span>
                </div>
            @else
                <div class="input-group">
                    <input class="form-control" placeholder="Email 地址" id="subscribe-input">
                    <span class="input-group-btn">
                        <button class="btn btn-danger btn-" id="subscrib-btn" type="button">
                            <i class="fa fa-arrow-right" aria-hidden="true"></i> 开始订阅
                        </button>
                    </span>
                </div>
            @endif
        </form>
    </div>
</div>