app/Http/routes.php
<?php

# ------------------ Page Route ------------------------
Route::get('/', 'PagesController@home')->name('home');
Route::get('/feed', 'PagesController@feed')->name('feed');
Route::get('/sitemap', 'PagesController@sitemap');
Route::get('/sitemap.xml', 'PagesController@sitemap');
Route::get('/search', 'PagesController@search')->name('search');

Route::group(['middleware' => ['auth', 'admin_auth']], function () {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

// Registration Routes... 请自行开启注册功能
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...  请自行开启注册功能
// Route::get('password/reset', 'Auth\PasswordController@getEmail');
// Route::post('password/email', 'Auth\PasswordController@postEmail');
// Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
// Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::resource('users', 'UsersController', ['only' => ['show']]);
Route::resource('posts', 'PostController', ['only' => ['show', 'create', 'store', 'update', 'edit']]);
Route::resource('categories', 'CategoryController', ['only' => ['show']]);

Route::resource("issues","IssueController", ['only' => ['show', 'index']]);

resources/views/common/_posts.blade.php
@foreach ($posts as $post)
    <article class="post grid-item">
        <div class="article-wrap">
            <div class="featured-media">
                <a href="{{ route('posts.show', [$post->id]) }}">
                    <img src="{{ img_crop($post->cover, 720, 376) }}" alt="{{ $post->title }}">
                </a>
            </div>
            <div class="post-head">
                <h1 class="post-title"><a href="{{ route('posts.show', [$post->id]) }}">{{ $post->title }}</a></h1>
            </div>
            <div class="post-content">
                <p>{{ $post->excerpt }}</p>
            </div>

            <footer class="post-footer clearfix">
                <div class="pull-left tag-list">
                    <a href="{{ route('categories.show', [$post->category->id]) }}"><i class="fa fa-folder-open-o"></i> {{ $post->category->name }}</a>
                    <a href="{{ route('users.show', [$post->user->id]) }}"><span class="author"><i class="fa fa-user" aria-hidden="true"></i> {{ $post->user->name }}</a></span>
                    <time class="post-date" title="{{ $post->created_at->diffForHumans() }}"><i class="fa fa-clock-o" aria-hidden="true"></i> {{ $post->created_at->diffForHumans() }}</time>
                </div>
            </footer>
        </div>
    </article>
@endforeach